// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBipY5WdZYQNeWldcQ1T_L1mC7DK_RQcwU',
    appId: '1:1007286031823:web:6d316b259086388fc2aeba',
    messagingSenderId: '1007286031823',
    projectId: 'loginbackend-51be1',
    authDomain: 'loginbackend-51be1.firebaseapp.com',
    storageBucket: 'loginbackend-51be1.firebasestorage.app',
    measurementId: 'G-40J71EPQFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyS4t8qn9CiGO_0Vg9gxkCx_xlOCBqt0U',
    appId: '1:1007286031823:android:3674bae91a8751b7c2aeba',
    messagingSenderId: '1007286031823',
    projectId: 'loginbackend-51be1',
    storageBucket: 'loginbackend-51be1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDeC_4Zlt2DOYXj7FH0pWl7yJK9oQQS4',
    appId: '1:1007286031823:ios:2ada459226449e40c2aeba',
    messagingSenderId: '1007286031823',
    projectId: 'loginbackend-51be1',
    storageBucket: 'loginbackend-51be1.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDeC_4Zlt2DOYXj7FH0pWl7yJK9oQQS4',
    appId: '1:1007286031823:ios:2ada459226449e40c2aeba',
    messagingSenderId: '1007286031823',
    projectId: 'loginbackend-51be1',
    storageBucket: 'loginbackend-51be1.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBipY5WdZYQNeWldcQ1T_L1mC7DK_RQcwU',
    appId: '1:1007286031823:web:fc044305e5b8a76bc2aeba',
    messagingSenderId: '1007286031823',
    projectId: 'loginbackend-51be1',
    authDomain: 'loginbackend-51be1.firebaseapp.com',
    storageBucket: 'loginbackend-51be1.firebasestorage.app',
    measurementId: 'G-ZDKRK6G6EN',
  );
}
